[package]
name = "always-success"
version = "1.0.0"
edition = "2021"

[features]
dev = []
local = []
testnet = []
mainnet = []

[dependencies]
ckb-std = { git = "https://github.com/XuJiandong/ckb-std.git", branch = "load-library-typeid" }
