[package]
name = "account-cell-type"
version = "1.5.0"
edition = "2018"

[features]
dev = ["das-core/dev"]
local = ["das-core/local"]
testnet = ["das-core/testnet"]
mainnet = ["das-core/mainnet"]

[dependencies]
ckb-std = "0.9.0"
das-core = { path = "../../libs/das-core", default-features = false }
das-map = { path = "../../libs/das-map", default-features = false }
das-types = { path = "../../../das-types/rust", default-features = false }
das-dynamic-libs = { path = "../../libs/das-dynamic-libs" }
