[workspace]
members = [
    "tests",
    "libs/das-core",
    "libs/das-sorted-list",
    "contracts/always-success",
    "contracts/config-cell-type", "contracts/apply-register-cell-type",
]

[profile.release]
overflow-checks = true
opt-level = 's'
lto = true
codegen-units = 1
panic = 'abort'
