[workspace]
members = [
    "tests",
    "libs/das-core",
    "libs/das-sorted-list",
    "libs/das-map",
    "libs/eip712",
    "contracts/always-success",
    "contracts/apply-register-cell-type",
    "contracts/account-cell-type",
    "contracts/account-sale-cell-type",
    "contracts/account-auction-cell-type",
    "contracts/balance-cell-type",
    "contracts/config-cell-type",
    "contracts/income-cell-type",
    "contracts/pre-account-cell-type",
    "contracts/proposal-cell-type",
    "contracts/reverse-record-cell-type",
    "contracts/offer-cell-type",
]

[profile.release]
overflow-checks = true
opt-level = 's'
lto = true
codegen-units = 1
panic = 'abort'
