[workspace]
members = [
    # Common libs
    "libs/das-core",
    "libs/das-dynamic-libs",
    "libs/das-map",
    "libs/das-sorted-list",
    "libs/eip712",
    # Contracts
    "contracts/always-success",
    "contracts/account-cell-type",
    "contracts/account-sale-cell-type",
    "contracts/account-auction-cell-type",
    "contracts/apply-register-cell-type",
    "contracts/balance-cell-type",
    "contracts/config-cell-type",
    "contracts/income-cell-type",
    "contracts/offer-cell-type",
    "contracts/pre-account-cell-type",
    "contracts/proposal-cell-type",
    "contracts/reverse-record-cell-type",
    "contracts/reverse-record-root-cell-type",
    "contracts/sub-account-cell-type",
    "contracts/eip712-lib",
    # Only for unit tests
    "tests",
    "contracts/test-env",
    "contracts/test-custom-script",
    "contracts/playground",
]

[workspace.dependencies]
das-types = { git = "ssh://git@github.com/dotbitHQ/das-types-private.git", default-features = false, rev = "cccfabfe2e" }
simple-ast = { git = "ssh://git@github.com/dotbitHQ/simple-ast.git", features = [ "no_std" ], default-features = false, rev = "6250d4dbe6" }
das-map = { path = "libs/das-map", default-features = false }
das-core = { path = "libs/das-core", default-features = false }
das-sorted-list = { path = "libs/das-sorted-list", default-features = false }
ckb-std = { git = "https://github.com/XuJiandong/ckb-std.git", rev = "872cd13b9b1974edb87418bc1b93ed970282aaa8" }

# Uncomment the patches below for local development
[patch."ssh://git@github.com/dotbitHQ/simple-ast.git"]
simple-ast = { path = "../simple-ast", features = ["no_std"], default-features = false }

[patch."ssh://git@github.com/dotbitHQ/das-types-private.git"]
das-types = { path = "../das-types/rust", default-features = false }

[profile.release]
overflow-checks = true
opt-level = 2
lto = true
codegen-units = 1
panic = 'abort'
