[workspace]
members = [
    "tests",
    "libs/das-bloom-filter",
    "libs/das-core",
    "libs/das-sorted-list",
    "libs/das-wallet",
    "contracts/always-success",
    "contracts/apply-register-cell-type",
    "contracts/account-cell-type",
    "contracts/config-cell-type",
    "contracts/income-cell-type",
    "contracts/pre-account-cell-type",
    "contracts/proposal-cell-type",
    "tools/calculator",
]

[profile.release]
overflow-checks = true
opt-level = 's'
lto = true
codegen-units = 1
panic = 'abort'
