[package]
name = "config-cell-type"
version = "0.1.0"
edition = "2018"

[dependencies]
ckb-std = "0.7.1"
hex = { default-features = false, version = "0.4.2"}
das-core = { path = "../../libs/das-core" }
das-types = { path = "../../../das-types/rust", default-features = false }
