[package]
name = "calculator"
version = "1.0.0"
authors = ["Link <link@blockabc.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.2"
