[package]
name = "eip712-lib"
version = "1.0.0"
edition = "2018"

[features]
dev = ["das-core/dev", "eip712/dev"]
local = ["das-core/local", "eip712/local"]
testnet = ["das-core/testnet", "eip712/testnet"]
mainnet = ["das-core/mainnet", "eip712/mainnet"]

[dependencies]
ckb-std = "0.10.0"
das-core = { path = "../../libs/das-core", default-features = false }
das-types = { path = "../../../das-types/rust", default-features = false }
das-map = { path = "../../libs/das-map", default-features = false }
eip712 = { path = "../../libs/eip712" }
