[net]
git-fetch-with-cli = true

# [build]
# target = "riscv64imac-unknown-none-elf"
# incremental = true

# [target."riscv64imac-unknown-none-elf"]
# rustflags = ["-Z", "pre-link-arg=-zseparate-code", "-Z", "pre-link-arg=-zseparate-loadable-segments"]
