[net]
git-fetch-with-cli = true

[build]
# target = "riscv64imac-unknown-none-elf"
incremental = true

[target."riscv64imac-unknown-none-elf"]
rustflags = ["-Z", "pre-link-arg=-zseparate-code", "-Z", "pre-link-arg=-zseparate-loadable-segments"]
# [patch."ssh://git@github.com/dotbitHQ/simple-ast.git"]
# das-types = { git = "ssh://git@github.com/dotbitHQ/das-types-private.git", rev = "37e79f3f2bd945fdc29ec9a61fa4577c8d575c8e", optional = true }
# das-types-std = { git = "ssh://git@github.com/dotbitHQ/das-types-private.git", rev = "ff313f9f95d496032f3100ecc6be28a95ec5c5b3", optional = true }

# Uncomment the following patches to use the local source codes
# WARNING! Because the project is compiling in a container, so the .cargo must be put in here.
# [patch."ssh://git@github.com/dotbitHQ/das-types-private.git"]
# das-types-std = { path = "../das-types-std/rust" }
# das-types = { path = "../das-types/rust" }

# [patch."ssh://git@github.com/dotbitHQ/simple-ast.git"]
# simple-ast = { path = "../simple-ast" }
