[net]
git-fetch-with-cli = true

[build]
# target = "riscv64imac-unknown-none-elf"
incremental = true

[target."riscv64imac-unknown-none-elf"]
rustflags = ["-Z", "pre-link-arg=-zseparate-code", "-Z", "pre-link-arg=-zseparate-loadable-segments"]

# Uncomment the following patches to use the local source codes
# WARNING! Because the project is compiling in a container, so the .cargo must be put in here.
# [patch."https://github.com/dotbitHQ/das-types-private.git"]
# das-types-std = { path = "../das-types-std/rust" }
# das-types = { path = "../das-types/rust" }
